version: "3.8"
services:
  angular:
    build:
      context: angular
    ports:
      - "4200:4200"
    volumes:
      - ./..:/e-karta-zdrowia
    tty: true
    networks:
      - e-karta-zdrowia
networks:
  e-karta-zdrowia:
