export enum Image {
  UNDRAW_STABILITY_BALL = 'UNDRAW_STABILITY_BALL',
  UNDRAW_WORKING_OUT = 'UNDRAW_WORKING_OUT',
  UNDRAW_EXPLORING = 'UNDRAW_EXPLORING',
  UNDRAW_NOT_FOUND = 'UNDRAW_NOT_FOUND',
  UNDRAW_HEALTHY_LIFESTYLE = 'UNDRAW_HEALTHY_LIFESTYLE',
  FITNESS_LOGO = 'FITNESS_LOGO',
}
