export enum RoutePath {
  DASHBOARD = 'DASHBOARD',
  EMPLOYEES = 'EMPLOYEES',
  GUIDEBOOK = 'GUIDEBOOK',
  GYMS = 'GYMS',
  NOT_FOUND = 'NOT_FOUND',
  ROOT = 'ROOT',
  SETTINGS = 'SETTINGS',
  SIGN_IN = 'SIGN_IN',
}
