export enum RoutePath {
  DASHBOARD = 'DASHBOARD',
  GUIDEBOOK = 'GUIDEBOOK',
  NOT_FOUND = 'NOT_FOUND',
  ROOT = 'ROOT',
  SETTINGS = 'SETTINGS',
  SIGN_IN = 'SIGN_IN',
  TRAININGS = 'TRAININGS',
  TRAINING_ADD = 'TRAINING_ADD',
}
