export enum RoutePath {
  DASHBOARD = 'DASHBOARD',
  GUIDEBOOK = 'GUIDEBOOK',
  NOT_FOUND = 'NOT_FOUND',
  PATIENTS = 'PATIENTS',
  ROOT = 'ROOT',
  SETTINGS = 'SETTINGS',
  SIGN_IN = 'SIGN_IN',
  SIGN_OUT = 'SIGN_OUT',
}
