export enum Icon {
  BELL = 'BELL',
  BUILDING = 'BUILDING',
  USERS = 'USERS',
  CREDIT_CARD = 'CREDIT_CARD',
  GEAR_WIDE_CONNECTED = 'GEAR_WIDE_CONNECTED',
  RECORD = 'RECORD',
  RECORD_PARTIALLY_FILL = 'RECORD_PARTIALLY_FILL',
  DASHBOARD = 'DASHBOARD',
}
